### ISSUE TITLE
use container aliases instead of endpoint.of

### ISSUE THREAD

**Issue by doktordirk** [SpoonX/aurelia-api#111]
like https://github.com/SpoonX/aurelia-config/pull/2 registering aliases with the container might be easier/better

**Comment by doktordirk** [comment]
so as detault it.ll be like @inject('github-rest', 'temp-local', 'alerts-websocket'); so, name-transport or so

**Comment by RWOverdijk** [comment]
If this is a feature you want, then sure. But I'm personally sticking to the resolver. I think it's more elegant than global container string magic.

**Comment by doktordirk** [comment]
probably not gonna do this
