### ISSUE TITLE
Trailing Slashes

### ISSUE THREAD

**Issue by CoinBR** [SpoonX/aurelia-api#140]
The API I'm accessing, always redirects me to a path with trailing slashes.

For example, it try aceesing this urls:
http://url.com/api/product
http://url.com/api/product/3

I get redirected to those paths, respectively:
http://url.com/api/product/
http://url.com/api/product/3/

The thing is, aurelia-api always never uses trailing slashes, and I end up getting this error:

> Fetch API cannot load http://localhost:8000/api/v1/product/3. The request was redirected to 'http://url.com/api/v1/product/3/', which is disallowed for cross-origin requests that require preflight.

Yeah, I know that this is a CORS limitation/security_measure.
But I think it is really use to address this situation in aurelia-api. Having the option to add the trailing slash, shouldn't be a big deal.

Thank you very for your time, btw =)

**Comment by CoinBR** [comment]
Ok, I just had my go horse moment.

I've made the 'request' function (on rest.js) return that instead:
`      return this.client.fetch(path + '/', requestoptions).then(function (response) {`

Would be nice to have it properly implemented anyway. I would that myself, but I'm just starting with aurelia-api, and I'm not familiar with its semantics. Haven't even done a POST yet.

**Comment by doktordirk** [comment]
would the proposed solution work for you

**Comment by CoinBR** [comment]
Great Job =)  
That works great for me!
Thank you ;D
