### ISSUE TITLE
the getRequestPath does not allow something like resource/id?option=foo

### ISSUE THREAD

**Issue by ricbermo** [SpoonX/aurelia-api#149]
I've been trying to send the access_token in the url without success. Checking and the source code I could see the getRequestPath function does not transforms properly the criteria.

Going back to my example, sending query parameters and and ID to fetch a resource is not possible.

doing something like `apiEndpoint.find('users', 1, {token: asdasdads});` only returns `users/1`; the access option is lost.

**Comment by doktordirk** [comment]
usually one can do {id:1, token:rytr} instead. can.t you?

**Comment by doktordirk** [comment]
ps: criteria is for the uri and options for fetch options eg headers

**Comment by ricbermo** [comment]
{id:1, token:rytr} will generate `?id=....&token=.....`

**Comment by doktordirk** [comment]
yes, that's what i meant. your server doesn't accept that?

**Comment by ricbermo** [comment]
well it's a restful api.

**Comment by doktordirk** [comment]
well, i think there would be two options. use find(path/id, criteria) or we add a findOne(path, id, criteria)
