### ISSUE TITLE
Rest.post function submits raw string requests

### ISSUE THREAD

**Issue by alxwest** [SpoonX/aurelia-api#154]
Hi I found an issue with Rest.post submitting requests with raw strings yet the header is "application/json".

My user case is I need to submit a URL to a REST service. Using Rest's post function creates a request with a raw string body. The REST service's JSON parser rightly thinks the URL is a JSON object due to the colon after http.

**Comment by alxwest** [comment]
I've created a fix and submitted in PR #155.

**Comment by doktordirk** [comment]
i wouldn't want to stringify a body x=x. that'll be then 0=h&1=%3D&2=h

**Comment by alxwest** [comment]
@doktordirk Do you mean when stringifying form data?

**Comment by doktordirk** [comment]
more like stringifying allready stringified data. you stringify just everything there. a user might do
rest.post(url, 'x=y'), so the body is stringified already

**Comment by alxwest** [comment]
I see. My original problem is I expected the aurelia-api to send valid JSON as it works out to append the "content-type:application\json" header for a raw string. Shouldn't it send "text\plain" or parse the string in to JSON?

**Comment by doktordirk** [comment]
we cannot cover all options. hence, we use 'sensible' defaults and most rest apis use JSONs. hence, the default content-type is application/json and objects get json.stringified. 

for all other options, one would need to set the content-type oneself (see docs) and submit an appropriately transformed body

**Comment by RWOverdijk** [comment]
I don't understand the use case. @doktordirk do you?

**Comment by doktordirk** [comment]
not really. the PR JSON.stringify when the body isn.t an Object which makes no sense

**Comment by RWOverdijk** [comment]
@alxwest What are you trying to accomplish? Maybe we can help. I don't understand the question entirely.

**Comment by alxwest** [comment]
I 'm sending a string value to a REST api that only supports valid JSON. Using the following code.

` this.apiEndpoint.post('api/values', 'somevalue');`

Aurelia-api submits the request below.
```
POST example.com/api/values HTTP/1.1
...
content-type: application/json

somevalue
```
The body is not valid JSON but the following request is

```
POST example.com/api/values HTTP/1.1
...
content-type: application/json

"somevalue"
```

I assumed that aurelia-api would send valid JSON if it composed the request to use content-type application/json.

**Comment by doktordirk** [comment]
@alxwest how would it make a json from just a string? what's the key what's the value. minimum would be like
this.apiEndpoint.post('api/values', {'key':'value'})

**Comment by alxwest** [comment]
@doktordirk Normally a string surrounded in quotes is parsed as a primitive string by most JSON parsers (that aren't set to strict).

**Comment by RWOverdijk** [comment]
@alxwest Normally a string surrounded by quotes is a string, where it contains quotes as a string. JSON is a string, without additional quotes surrounding it.

**Comment by RWOverdijk** [comment]
Also, a "word" as a string is not valid json.

**Comment by doktordirk** [comment]
so i case you need that, you'll need to use your own fork or change the Rest.prototype.request in your app to your liking
