### ISSUE TITLE
Add ability to set Default host name

### ISSUE THREAD

**Issue by fedoranimus** [SpoonX/aurelia-api#158]
It would be great if we could configure the default host name for endpoints.

Having to prepend a host name other than the current client url is a bit tedious and error-prone.

If this is already available, please let me know.

**Comment by doktordirk** [comment]
we are open to PRs :smile: so maybe adding a baseUrl to Config which is prepended if the endpoint doesn't contain a protocol?

**Comment by fedoranimus** [comment]
Working on it.

**Comment by fedoranimus** [comment]
Feature PR merged into Master.
