### ISSUE TITLE
Requesting non JSON content

### ISSUE THREAD

**Issue by cb-fred** [SpoonX/aurelia-api#166]
Hi, It doesn't seem possible to request an URL that returns non-JSON content as by line 71 of `/src/rest.js` all responses are parsed as json. It seems to me that this should only be done if the `Accept` header is `application/json`. Any toughts ?

**Comment by doktordirk** [comment]
hmm. maybe on response content-type.

**Comment by RWOverdijk** [comment]
Closing this for now. If this is still relevant, feel free to reopen the issue.

Note: this is a copy-paste comment to clean up the issues. It's not personal, and I didn't review the issue before posting this. They're all outdated and I need a way to figure out what's still relevant.

Thank you for understanding :)
