### ISSUE TITLE
"getEndpoint is not a function"

### ISSUE THREAD

**Issue by ibnuda** [SpoonX/aurelia-api#184]
Hello there.
I have a problem when I use this library.

As per official guideline, the library configuration in my `main.ts` is something like this.
```
  aurelia.use
    .plugin('aurelia-api', config => {
      config.registerEndpoint('api', 'https://some.api.site');
    });
```
and in one of the class
```

    constructor(conn: Config, private ea: EventAggregator)  {
      this.apiEndpoint = conn.getEndpoint('api');
      // snip...
     return this.apiEndpoint.find(params.kos).then(ids => // snip.
```
but I got an error about `getEndpoint is not a function`. And here's the part of the generated app-bundle.js from the snippet above.
```
            this.apiEndpoint = conn.getEndpoint('api');
            ea.subscribe(something_1.Something, function (msg) {
                var ids = msg.what;
                Object.assign(_this.ids, ids);
            });
```
Thank you for your explanation.

**Comment by doktordirk** [comment]
is it the right Config class there?

**Comment by ibnuda** [comment]
Yes.

**Comment by doktordirk** [comment]
what i mean is, conn apparently isn.t an instance of `import {Config} from 'aurelia-api'` since then it.d had that function. something is wrong with your (auto)inject or the way you create  instances of that

**Comment by ibnuda** [comment]
I'm sorry if the following sentence is unhelpful, but after I delete my `node_modules` directory and reinstall the modules, it works fine.
May I close this issue?
