### ISSUE TITLE
dynamicaly reconfigure endpoints

### ISSUE THREAD

**Issue by k2s** [SpoonX/aurelia-api#185]
What is the best way to reconfigure endpoint when Aurelia app was already configured ?

**Comment by RWOverdijk** [comment]
@k2s That's a very good question.

Simply require the config from aurelia-api and call [.registerEndpoint()](https://github.com/SpoonX/aurelia-api/blob/master/src/config.js#L55).

If you really want to _reconfigure_ an endpoint for some reason (I'm curious when you'd want to do this) you'll have to work with [.getEndpoint()](https://github.com/SpoonX/aurelia-api/blob/master/src/config.js#L104) and manual actions. If this really is a feature people need often, we can create a convenience method for it.

**Comment by k2s** [comment]
what worked for me:
```
import { Container } from 'aurelia-framework'
import { Config as AureliaApi } from 'aurelia-api'
...
let configApi = Container.instance.get(AureliaApi)
configApi.getEndpoint('apiU').defaults.headers.myheader = 'ok'
```
