### ISSUE TITLE
Make buildQueryString second parameter 'traditional' configurable

### ISSUE THREAD

**Issue by MayGo** [SpoonX/aurelia-api#187]
Problem:

```js
let params={mylist:["one", "two", "three"]};
this.apiEndpoint.find('something', params);
```

Makes query `?mylist[]=one&mylist[]=two&mylist[]=three`.

but is needed query `?mylist=one&mylist=two&mylist=three`.

aurelia-api uses aurelia-path function buildQueryString(params, traditional), that makes query the way it is needed when traditional = true.

Needed feature:

Provide a way to configure buildQueryString-s traditional parameter.

**Comment by RWOverdijk** [comment]
@MayGo Nice. We can add this to the endpoint configuration. Would you like to submit a PR?

**Comment by MayGo** [comment]
yes, i will try.

**Comment by MayGo** [comment]
duplicate #175 
not released yet

**Comment by RWOverdijk** [comment]
@MayGo This is part of another issue we're working on. Publishing has to hold until we fix the babel issue. Shouldn't be too long now :)
