### ISSUE TITLE
passing date parameter

### ISSUE THREAD

**Issue by jrabalais** [SpoonX/aurelia-api#191]
I just did a jspm update and now every place I pass a date value with your api, the date value does not get passed.

See below code example:
return this.endpoint.find('scheduling/scheduleentry', { shiftDate : shiftDate, shiftId : shiftId })
                        .then(response => {
                            return response;
                        }).catch(console.error);

Below is the error I'm getting showing only shiftId is getting sent:
aurelia-fetch-client.js:140 GET http://localhost:1672/api/scheduling/scheduleentry?shiftId=1 500 (Internal Server Error)

**Comment by RWOverdijk** [comment]
@jrabalais So it worked before? Could you tell me which version worked?

**Comment by jrabalais** [comment]
Yes, I was on 3.0.0-rc4 prior to my update.  I reverted back to that for now and it's working again.

**Comment by RWOverdijk** [comment]
That's odd. Have you been able to find the cause? It appears to be working for me. If not, could you provide me with a code snippet so I can reproduce it?

**Comment by jrabalais** [comment]
Not sure what more I could send.

The only other thing I can think of is the date is coming from from a Kendo
date control via the Kendo Aurelia Bridge project.

If you want, I can incrementally update the package until I find the exact
update that breaks it...

**Comment by RWOverdijk** [comment]
@jrabalais That would be of great help. A console log of the thing you're trying to send would also help.

**Comment by jrabalais** [comment]
The issue occurred sometime between rc4 and rc7.  I am unable to pull down
rc5 and rc6 anymore with jspm.

Please see the attached logs for each version.

**Comment by jrabalais** [comment]
Here's more of my code if that helps.

*ViewModel Code:*
    onShiftSelect(e) {
        let dataItem = this.shiftsDropdownList.dataItem(e.item);
        this.shift = dataItem;
        this.currentDateEnabled = dataItem.id != '';
        if(dataItem.id != '') {
            // Will provide this value in screenshot.
            // Using Kendo UI date picker
            alert(this.rosterDatePicker.value());
            this.schedulingFactory.getAllScheduleEntries(dataItem.id,
this.rosterDatePicker.value()).then(entries => this.scheduleEntries =
entries);
            this.schedulingFactory.getAllUnitScheduleEntries(dataItem.id,
this.rosterDatePicker.value()).then(entries => this.unitScheduleEntries =
entries);
        }
        else {
            this.scheduleEntries = null;
        }
    }

*Factory Code:*
    getAllScheduleEntries(shiftId, shiftDate) {
        return this.endpoint.find('scheduling/scheduleentry', { shiftId :
shiftId, shiftDate : shiftDate })
                        .then(response => {
                            return response;
                        }).catch(console.error);
    }

*Screenshot of Alert:*

*[image: Inline image 1]*

**Comment by jrabalais** [comment]
Any info on this issue?

**Comment by RWOverdijk** [comment]
@jrabalais We'll look into this shortly. In the meantime, maybe you can take a look yourself? The code isn't that terrifyingly difficult :)

**Comment by RWOverdijk** [comment]
Also, attachments don't work. So best answer on github :)

**Comment by doktordirk** [comment]
reminds me of https://github.com/SpoonX/aurelia-api/pull/157

**Comment by doktordirk** [comment]
tested it and should work fine
