### ISSUE TITLE
Endpoint.of() typing should resolve to Rest

### ISSUE THREAD

**Issue by obust** [SpoonX/aurelia-api#196]
The aurelia-api typings mention that `Endpoint.of()` resolve to a `Endpoint` when it is actually a `Rest` instance if I am not mistaking:

```ts
/**
 * Endpoint class. A resolver for endpoints which allows injection of the corresponding Rest client into a class
 */
export declare class Endpoint {
  
  /**
     * Construct the resolver with the specified key.
     *
     * @param {string} key
     */
  constructor(key: string);
  
  /**
     * Resolve for key.
     *
     * @param {Container} container
     *
     * @return {Rest}
     */
  get(container: Container): Rest;
  
  /**
     * Get a new resolver for `key`.
     *
     * @param {string} key  The endpoint name
     *
     * @return {Endpoint}  Resolves to the Rest client for this endpoint
     */
  static of(key: string): Endpoint; //****** this should resolve to Rest *******
}
```

**Comment by AdamWillden** [comment]
This has caught me out before but now I remember without checking docs that it is indeed Rest

**Comment by RWOverdijk** [comment]
Uh-oh, that's wrong then... @obust mind doing a quick pr to fix it? It's a typing in src.

**Comment by MarcScheib** [comment]
If no `key` is given to `of()`, it returns the default endpoint. Hence, shouldn't it be `of(key?: string): Rest`?

**Comment by RWOverdijk** [comment]
Yes :)

**Comment by MarcScheib** [comment]
I create a PR for the optional key. The return type, in my opionion, is correct. In the end, you get `Rest` injected of course, which results from `get()` (aurelia-di is doing the magic there).

**Comment by RWOverdijk** [comment]
Closing this for now. If this is still relevant, feel free to reopen the issue.

Note: this is a copy-paste comment to clean up the issues. It's not personal, and I didn't review the issue before posting this. They're all outdated and I need a way to figure out what's still relevant.

Thank you for understanding :)
