### ISSUE TITLE
Header not being applied

### ISSUE THREAD

**Issue by fedoranimus** [SpoonX/aurelia-api#197]
Adding a Content-Type header as below:

```
config.registerEndpoint('auth', 'http://localhost:5000/connect/', { 
          headers: { 'Content-Type': 'application/x-www-form-urlencoded' }
        }
);
```
However, my request is still using the default Content-Type of 'application/json'. Note: This endpoint is being used by Aurelia-Authentication as well, issue could be in there?

Edit: Fixed formatting

**Comment by RWOverdijk** [comment]
This is an issue that was resolved, I'll have to dig a bit to find the answer. It had something to do with refresh tokens. Is that the case for you?

**Comment by fedoranimus** [comment]
I'm trying to get a connect token, but will need a refresh token eventually from the same endpoint.

**Comment by fedoranimus** [comment]
I assume you're referring to this? https://github.com/SpoonX/aurelia-authentication/issues/350

**Comment by fedoranimus** [comment]
Yes, using that configuration option solves the issue.

**Comment by RWOverdijk** [comment]
Ah! That's good. :) This should probably default to the headers set. I think this feature is cool, but the defaults are wrong.

**Comment by RWOverdijk** [comment]
Closing this for now. If this is still relevant, feel free to reopen the issue.

Note: this is a copy-paste comment to clean up the issues. It's not personal, and I didn't review the issue before posting this. They're all outdated and I need a way to figure out what's still relevant.

Thank you for understanding :)
