### ISSUE TITLE
Allow the resource path to contain query parameters

### ISSUE THREAD

**Issue by mreiche** [SpoonX/aurelia-api#201]
In several setups, I don't have to possibility to activate rewriting for ReSTful API pathes, so I have to setup the API endpoint like following:

```javascript
this.fetchClient.baseUrl = backend.basepath+'/api/index.php?_p=';
```

But this fails when trying to ``find()`` in `aurelia-orm` with criteria:

```javascript
this.assetRepository.find({criteria:1}).then(assets=>{
    // assets
});
```

requests to `http://dev-server/api/index.php?_p=/assets?criteria=1`

**Comment by mreiche** [comment]
Its propable better to use `url-parse` for creating/generating URLs.
import URL from 'url-parse';
```javascript
function getRequestPath(resource: string, traditional: boolean, idOrCriteria?: string|number|{}, criteria?: {}) {
	let resourcePath = new URL(resource,true);
	let hasSlash = resourcePath.pathname.slice(-1) === '/';
	
	if (typeof idOrCriteria === 'string' || typeof idOrCriteria === 'number') {
		criteria = idOrCriteria
	}
	
	if (typeof criteria === 'object' && criteria !== null) {
		for (let key in criteria) {
			resourcePath.query[key] = criteria[key];
		}
	} else {
		resourcePath.pathname+=(hasSlash === false ? '/' : '')+criteria;
	}
	return resourcePath.toString();
}
```
PRO: its cleaner and much more easier to read.
CON: `traditional` parameter currently not implemented.

**Comment by RWOverdijk** [comment]
I personally don't want to do that. I think this is a very specific problem, and maybe it should be handled differently. What we _can_ do is search for a question mark in the base URL, and use either ampersand or question mark based on that result.

**Comment by mreiche** [comment]
This is a very common problem in PHP environments, where you need to enable rewriting on the webserver.

**Comment by RWOverdijk** [comment]
@mreiche IMO, It's a very outdated problem to have... But that's not relevant to this issue :)

**Comment by mreiche** [comment]
Im working on projects with legacy code older than 13 years. This is an outdated but still present problem.

**Comment by RWOverdijk** [comment]
@mreiche I don't envy you :p
