### ISSUE TITLE
PATCH instead of PUTfor update of a resource

### ISSUE THREAD

**Issue by bzd2000** [SpoonX/aurelia-api#203]
Hi,

I noticed that currently a PUT is done for the update of a resource.
Wouldn't it better to use the PATCH method?

If you agree, I make a PR.

kr,
Filip.

**Comment by RWOverdijk** [comment]
@bzd2000 It depends on the server. Seeing how the _entire_ entity is sent to the server as a payload, I opted to use PUT. But I suppose it can be made configurable with both options (PUT as the default for BC). So that would definitely be worth a PR!

**Comment by doktordirk** [comment]
we have patch and patchOne for that already. https://github.com/SpoonX/aurelia-api/blob/master/src/rest.js#L168
 given that, still want to make update and updateOne optionally using patch?

**Comment by RWOverdijk** [comment]
Closing this for now. If this is still relevant, feel free to reopen the issue.

Note: this is a copy-paste comment to clean up the issues. It's not personal, and I didn't review the issue before posting this. They're all outdated and I need a way to figure out what's still relevant.

Thank you for understanding :)
