### ISSUE TITLE
Unable to find module with ID: aurelia-api when using Webpack Skeleton and Visual Studio

### ISSUE THREAD

**Issue by robscottnh** [SpoonX/aurelia-api#204]
I'm sure that there's some sort of workaround at this point, but after several hours of research I'm stumped on how to proceed to resolve this.

I've installed using npm install aurelia-api -- save and see a corresponding entry in my package.json file:

    "aurelia-api": "3.1.1" ,

I've added the following to boot.ts:

aurelia.use
    .standardConfiguration()
   ...
    .plugin(PLATFORM.moduleName("aurelia-api", (config:any) => {...}))

However, when I run the app I get the following error:

Uncaught (in promise) Error: Unable to find module with ID: aurelia-api
    at WebpackLoader.<anonymous> (aurelia-loader-webpack.js:187)
    at step (aurelia-loader-webpack.js:36)
    ...

**Comment by RWOverdijk** [comment]
That's strange. I haven't heard this before. I've asked the question in [our gitter channel](https://gitter.im/SpoonX/Dev)

**Comment by robscottnh** [comment]
Thanks for following up.  I'll keep an eye out there and here.

**Comment by robscottnh** [comment]
It didn't look like anyone had an idea.  Am I right?

**Comment by MarcScheib** [comment]
I am using the plugin in my webpack app as well, without any errors. Can you provide some more code insight?

**Comment by robscottnh** [comment]
Hey Marc,

I'll try to get you some more info later today.. I'm travelling right now.
I really appreciate the time.

Rob

**Comment by robscottnh** [comment]
Marc,

Did you use a skeleton to create your project?  I'm trying to create a
minimal skeleton to show the problem.  (Not sure what was originally used
to create the code base I'm working on).

Regards,
Rob

**Comment by MarcScheib** [comment]
@robscottnh yes, basically I am using the webpack typescript sekeleton (no cli project).

**Comment by robscottnh** [comment]
Hey Marc,

Just getting back to this.  Do you have a link to the skeleton you used?  I
used one from here:

https://blogs.msdn.microsoft.com/webdev/2017/02/14/building-single-page-applications-on-asp-net-core-with-javascriptservices/#comments

I'm betting you used a different one.  I'd like to take a look at it.  My
guess is the webpack configs are different and that's probably where my
issue lies.

Thanks,
Rob

**Comment by doktordirk** [comment]
Could be:

From our install instructions:
```
Webpack
Run npm i aurelia-api --save from your project root.

Add 'aurelia-api' in the coreBundles.aurelia section of your webpack.config.js.
```

**Comment by RWOverdijk** [comment]
Closing this for now. If this is still relevant, feel free to reopen the issue.

Note: this is a copy-paste comment to clean up the issues. It's not personal, and I didn't review the issue before posting this. They're all outdated and I need a way to figure out what's still relevant.

Thank you for understanding :)
