### ISSUE TITLE
Environment based Endpoints

### ISSUE THREAD

**Issue by MarcScheib** [SpoonX/aurelia-api#21]
Hi,

would it be possible to implement endpoint selection based on environments?
What I would like to do is something like this:

```
config.registerEndpoint('dev', 'https://localhost);
config.registerEndpoint('stage', 'https://staging.xyz.de/');
config.registerEndpoint('production', 'https://xyz.de/');
config.setEnvironments({
        development: ['localhost'],
        stage: ['staging.xyz.de'],
        production: ['xyz.de']
      });
.setDefaultEndpoint(basedOnEnvironments);
```

The import part would be the setDefaultEndpoint(). Based on the param, I can tell your plugin to select the default endpoint based on my configured environments (which is more or less a mapping between hostname and endpoint). 
Perhaps it is also possible to skip the definition of environments and simply say, if I want an environment based default endpoint, search for the one with the correct hostname in all registered ones.

Best Regards
Marc

**Comment by RWOverdijk** [comment]
Hey @MarcScheib 

You could do that by setting up your own config file. That's what I do. I use a different config or my builds, that way it's all nicely grouped in a config. https://github.com/swanstack/aurelia-skeleton/blob/master/src/scripts/config/app.js

**Comment by MarcScheib** [comment]
Hi @RWOverdijk 

I do not understand exactly how I can build the automatic environment selection with this. Where is this happening? You only pass in your single server endpoint but where are the others ones from my example passed in? I don't want to switch them manually.

**Comment by MarcScheib** [comment]
I was rethinking a little bit. Is it the following you plan to do?

```
if (window.location.hostname contains stage.xyz.de)
    config = stage.xyz.de
else if (.... contains dev.xyz.de)
    config = dev.xyz.de

export default config;
```

**Comment by RWOverdijk** [comment]
@MarcScheib You don't. You usually wish to not publish dev info to production. That's why I suggested having a production.js config file and bundling that, in stead of development.js on dev. So you have separate environment specific configs.

**Comment by MarcScheib** [comment]
I would prefer not to adjust imports in my code for bundling regarding CI. 

Perhaps the better approach would be to have a sperate environment file which is not included in the bundle. Have one for dev, one for e.g. CI testing/building, and one for production. I think this is similar to what you do except I keep it unbundled and differing based on the deplyoment point. And we do no version control on this. What do you think about that?

**Comment by RWOverdijk** [comment]
I think you should do what feels best to you :) We use a combination.

* Server side, we use environment variables
* Client side we use a different config in our bundle (bundle.js)

I _really_ suggest you bundle the proper config. If you have dev, staging, beta and production environments you really want to split the configs and not expose them.
