### ISSUE TITLE
Unexpected end of JSON input

### ISSUE THREAD

**Issue by gregoryagu** [SpoonX/aurelia-api#212]
Any time that I make a call through aurelia-api/aurelia-orm, if I have the Chrome Sources tab open, it pauses on a promise rejection `SyntaxError: Unexpected end ofJSON input`

Everything actually works just fine.  It's just that this exception is thrown for every api call made even when there is no actual issue.  However, when debugging, this become cumbersome as it is always  thrown if an api call is made.  The json looks just fine:

`{"email":"Greg2@gmail.com","password":"Test","confirmPassword":"Test","appUserId":null}`

It would make debugging easier to resolve this. I have "Pause on Exception" selected, but not "Pause on caught exceptions" in the chrome debugger options. Any advice on this would be appreciated.

It breaks on this method in the debugger:

```
Rest.prototype.request = function request(method, path, body, options) {
    var requestOptions = (0, _extend2.default)(true, { headers: {} }, this.defaults, options || {}, { method: method, body: body });
    var contentType = requestOptions.headers['Content-Type'] || requestOptions.headers['content-type'];

    if ((typeof body === 'undefined' ? 'undefined' : _typeof(body)) === 'object' && body !== null && contentType) {
      requestOptions.body = /^application\/json/.test(contentType.toLowerCase()) ? JSON.stringify(body) : (0, _aureliaPath.buildQueryString)(body);
    }

    return this.client.fetch(path, requestOptions).then(function (response) {
      if (response.status >= 200 && response.status < 400) {
        return response.json().catch(function () {  //Debugger stops here.
          return null;
        });
      }

      throw response;
    });
  };

```

**Comment by doktordirk** [comment]
google reveals some results on fetch and this measage. happens either when the server returned null or cors settings don't match. nothing we can do here
