### ISSUE TITLE
Missing support for FormData posting

### ISSUE THREAD

**Issue by netcitylife** [SpoonX/aurelia-api#221]
Currently posting FormData does not work, when using standard default. 
```typescript
request(method: string, path: string, body?: {}, options?: {}, responseOutput?: { response: Response}): Promise<any|Error> {
    let requestOptions = extend(true, {headers: {}}, this.defaults, options || {}, {method, body});
    let contentType    = requestOptions.headers['Content-Type'] || requestOptions.headers['content-type'];

    // if body is object, stringify to json or urlencoded depending on content-type
    if (typeof body === 'object' && body !== null && contentType) {
      requestOptions.body = (/^application\/(.+\+)?json/).test(contentType.toLowerCase())
                          ? JSON.stringify(body)
                          : buildQueryString(body);
    }

    return this.client.fetch(path, requestOptions).then((response: Response) => {
      if (response.status >= 200 && response.status < 400) {
        if (responseOutput) {
          responseOutput.response = response;
        }

        return response.json().catch(() => null);
      }

      throw response;
    });
  }
```

As you see, requestOptions.body is always encoded when contentType is set, and it is set by default, and there is no way to "disable" in in a method call (post() for example). If I pass {headers: {'Content-type': undefined}} as options - it does not take effect, passing {headers: {'Content-type': null}} helps, encoding does not happen, but the underlying fetch() call works incorrectly with this Content-Type value. The best solution, as I think, is to check for FormData object passed as data and remove Content-Type header in this case...

**Comment by doktordirk** [comment]
yeah, aurelia-api/aurelia-fetch-client wasn't made for form data initially. we did enable it though see https://aurelia-api.spoonx.org/configuration.html
```
    // 4: Without endpoint defaults. Use this for FormData
    config.registerEndpoint('weather', 'https://weatherapi.io/', null);
```
and we have a formData submit test in /test

**Comment by RWOverdijk** [comment]
Closing this for now. If this is still relevant, feel free to reopen the issue.

Note: this is a copy-paste comment to clean up the issues. It's not personal, and I didn't review the issue before posting this. They're all outdated and I need a way to figure out what's still relevant.

Thank you for understanding :)
