### ISSUE TITLE
TS Definitions

### ISSUE THREAD

**Issue by alfkonee** [SpoonX/aurelia-api#29]
Are there any plans to add typescript definitions for this project

**Comment by RWOverdijk** [comment]
@alfkonee Yes there are :) I've set up the first test for aurelia-auth, and will apply the changes to all other repos soon.

**Comment by alfkonee** [comment]
That's great to hear by the way I tested the aurelia-auth set-up and it was working flawlessly one thing though
in typescript.js task
```
dtsGenerator.default({
    name   : 'aurelia-auth',
    project: paths.tmp,
    out    : paths.root + 'aurelia-auth.d.ts'
  });
```
I think you should include a main module so that the user imports from aurelia-auth instead of aurelia-auth/ index
like so
```
dtsGenerator.default({
    name   : 'aurelia-auth',
    project: paths.tmp,
    main: 'aurelia-auth/index',   
    out    : paths.root + 'aurelia-auth.d.ts'
  });
```

**Comment by doktordirk** [comment]
fixed https://github.com/SpoonX/aurelia-api/commit/2c59ae346a137919e62bf9d3edee36dfb90f98d2

**Comment by doktordirk** [comment]
typings still need work

**Comment by doktordirk** [comment]
fixed with https://github.com/SpoonX/aurelia-api/commit/da3d23a88d6c55373f214ecec8a9b013fe69f521

**Comment by alfkonee** [comment]
@doktordirk the fix for  external imports excludes external imports seems like a bug in babel-dts-generator how about we keep this open till we find a fix for that

**Comment by doktordirk** [comment]
i'm lost :smile: actually of have no idea about that d.ts stuff. so, if you say so, sure

**Comment by alfkonee** [comment]
@doktordirk Saw you post on the gitter of babel-dts-generator did you get any response from there that channel seems pretty quiet

**Comment by doktordirk** [comment]
yup. but i guess if asking someone directly one would get an answer

**Comment by alfkonee** [comment]
I think I found the problem it doesn't appear to be in babel-dts-generator but rather aurelia-tools especially with the `extractImports()` it removes only relative imports for obvious reasons 
I will see if I can extent this to filter the external imports futher

**Comment by alfkonee** [comment]
@doktordirk After much investigation I think the fixes are :+1: just needs a new release but still looking for better Typing generator that can show actual types on args and returns not just any
PS: Still investigating

**Comment by doktordirk** [comment]
i think way to go, is just to actually add them like aurelia does. isn't much work actually

**Comment by doktordirk** [comment]
a fix of the build tool is in the making

**Comment by doktordirk** [comment]
either the new babel-dts-builder is published then, or we just use it's code for better dts

**Comment by RWOverdijk** [comment]
@doktordirk https://github.com/YoloDev/babel-dts-generator this one? It was pushed 6 days ago

**Comment by doktordirk** [comment]
Yes. It.s merged aleady afaik

**Comment by doktordirk** [comment]
https://github.com/SpoonX/aurelia-api/pull/86
