### ISSUE TITLE
Add request defaults to readme

### ISSUE THREAD

**Issue by AdamWillden** [SpoonX/aurelia-api#33]
Am I correct that due to the [request function of rest.js](https://github.com/SpoonX/aurelia-api/blob/master/src/rest.js#L26) those two headers are in every request and therefore do not need adding as endpoint defaults?

If so I think it'd be worth adding a note to that effect on the readme.

**Comment by RWOverdijk** [comment]
I'm not sure what you mean. Which headers? You mean using json by default? I'd expect that to not be a problem.

**Comment by AdamWillden** [comment]
It's not a problem at all. It's very useful and what I think should be the default behaviour of aurelia fetch. I just didnt realise it was the case until I was looking at the source.  So my endpoints were all specifying those defaults needlessly

**Comment by RWOverdijk** [comment]
@AdamWillden Gotcha! You're right, we can add it in the readme :)

**Comment by AdamWillden** [comment]
I'll get round to adding this myself at some point. Just leave it here

**Comment by doktordirk** [comment]
fixed in https://github.com/SpoonX/aurelia-api/commit/8b9344d7cbac3ccd15f1cf05c8881d13b1e91c72

**Comment by AdamWillden** [comment]
:+1: you're awesome
