### ISSUE TITLE
problems with forks

### ISSUE THREAD

**Issue by doktordirk** [SpoonX/aurelia-api#53]
unnoticed forks of aurelia-api mess up authentication and orm. should have a way to warn users if they do . i'm thinking of a simple configured= true or something

**Comment by RWOverdijk** [comment]
`jspm inspect --forks` is a thing isn't it?

**Comment by doktordirk** [comment]
-> 'unnoticed forks'

**Comment by RWOverdijk** [comment]
What's that then?

**Comment by doktordirk** [comment]
eg someone installs orm normally and  aurelia-api as jspm easy-api=npm:aurelia-api.

**Comment by RWOverdijk** [comment]
Aside from "why would you do that", it could make sense. However, when you configure it, you already know you're using it right?

**Comment by doktordirk** [comment]
or maybe: ergo hardcoded aurelia-api dependency = bad. there was a post recently that allowed differently

**Comment by doktordirk** [comment]
different philosophy again. i'm more into spoon-feeding than your are

**Comment by RWOverdijk** [comment]
Haha fair enough

**Comment by doktordirk** [comment]
will actually be solved with the typo checks

**Comment by doktordirk** [comment]
will be fixed with https://github.com/SpoonX/aurelia-orm/pull/66 and https://github.com/SpoonX/aurelia-authentication/pull/72
