### ISSUE TITLE
Inversion of Control

### ISSUE THREAD

**Issue by doktordirk** [SpoonX/aurelia-api#54]
consider removing hard dependency on fetch client. see
http://blog.wolksoftware.com/the-current-state-of-dependency-inversion-in-javascript

**Comment by AdamWillden** [comment]
Thanks for the link, an interesting read (bookmarked).

**Comment by RWOverdijk** [comment]
I agree with IoC, that's why I wanted to import DOM in your other PR. This is a very easy thing to do.

**Comment by doktordirk** [comment]
yeah, but listens to an event added to well document actually. either ways, it' PAL, and the idea of it is to be a wrapper already

**Comment by RWOverdijk** [comment]
@doktordirk Yes, but again, using DI won't be a problem because it will just return _the thing_ without modifications. The only difference is that it allows you to extend or override DOM completely.

**Comment by doktordirk** [comment]
can make an issue there

**Comment by RWOverdijk** [comment]
It's just my way of saying, we can do the exact same thing, for the exact same reason with _fetch_. Unless that changed and I'm talking nonsense :p

**Comment by doktordirk** [comment]
would change all modules. that may not be wanted. but there is only one aurelia-composed event. but i guess one can find hypothetical scenarios with two different implementations of 'document'.

**Comment by RWOverdijk** [comment]
Would it, though? Because DI takes the instance and returns it if it doesn't have anything registered. The application wouldn't change. Which to me sounds like it's safe to change. I might not understand your reasoning though

**Comment by doktordirk** [comment]
as mentioned i have a hard time thinking today, so i might not even understand my reasoning myself. :smile: so, lets better continue another day.

**Comment by doktordirk** [comment]
aurelia.use.instance('endpointName', restInstance); could be of use

**Comment by RWOverdijk** [comment]
Closing this for now. If this is still relevant, feel free to reopen the issue.

Note: this is a copy-paste comment to clean up the issues. It's not personal, and I didn't review the issue before posting this. They're all outdated and I need a way to figure out what's still relevant.

Thank you for understanding :)
