### ISSUE TITLE
Using typescript shorthand autoinject

### ISSUE THREAD

**Issue by AdamWillden** [SpoonX/aurelia-api#89]
You cannot use `@autoinject` with `Endpoint.of('xyz')`. We should probably document the alternative method(s) mentioned here: https://gitter.im/SpoonX/Dev?at=57331f6733328697656261bd

I'll get round to this sometime in the next month! I haven't tested it yet either.

**Comment by AdamWillden** [comment]
@doktordirk You closing another issue reminded me about this. FWIW check out this:

https://github.com/aurelia/dependency-injection/pull/118
https://github.com/aurelia/dependency-injection/pull/111#issuecomment-231828722

Perhaps following suit with an `@endpointof('name')` decorator would work here? I'm open to suggestions regarding the decorator name.

**Comment by RWOverdijk** [comment]
Closing this for now. If this is still relevant, feel free to reopen the issue.

Note: this is a copy-paste comment to clean up the issues. It's not personal, and I didn't review the issue before posting this. They're all outdated and I need a way to figure out what's still relevant.

Thank you for understanding :)
